
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dbapp
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      name: dbapp
      labels:
        app: dbapp
    spec:
      containers:
        - name: dbapp
          image: rudzmic1/dbapp:1.0
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dbapp-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: dbapp
  ports:
  - port: 80
    targetPort: 5000
