apiVersion: v1
kind: Namespace
metadata:
  name: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-db
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      name: mysql-db
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:latest
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "appdb"
            - name: MYSQL_USER
              value: "appuser"
            - name: MYSQL_PASSWORD
              value: "www123"
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: mysql-db
  ports:
  - port: 3306
    targetPort: 3306