apiVersion: v1
kind: ReplicationController
metadata:
  name: firstapp-rc
spec:
  replicas: 3
  selector:
    app: firstapp
  template:
    metadata:
      name: firstapp
      labels:
        app: firstapp
    spec:
      containers:
        - name: firstapp
          image: rudzmic1/firstapp:1.0
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 5000