apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels:
    app: my-first-app
spec:
  containers:
    - name: my-first-pod-container
      image: rudzmic1/firstapp:1.0
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      ports:
        - containerPort: 5000

