apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pizza-deploment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzaapp
  template:
    metadata:
      name: pizzaapp
      labels:
        app: pizzaapp
    spec:
      containers:
        - name: pizzaapp
          image: rudzmic1/pizzaapp:1.0
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pizza-service
spec:
  type: ClusterIP
  selector:
    app: pizzaapp
  ports:
  - port: 80
    targetPort: 5000