apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shop-deploment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopapp
  template:
    metadata:
      name: shopapp
      labels:
        app: shopapp
    spec:
      containers:
        - name: shopapp
          image: rudzmic1/shopapp:1.0
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  type: ClusterIP
  selector:
    app: shopapp
  ports:
  - port: 80
    targetPort: 5000